/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class IOTest */

#ifndef _Included_IOTest
#define _Included_IOTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     IOTest
 * Method:    lwCConfine
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_IOTest_lwCConfine
  (JNIEnv *, jclass);

/*
 * Class:     IOTest
 * Method:    lwCCleanup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_IOTest_lwCCleanup
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
