/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LWCNI */

#ifndef _Included_LWCNI
#define _Included_LWCNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     LWCNI
 * Method:    lwCRegister
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_LWCNI_lwCRegister
  (JNIEnv *, jclass, jint);

/*
 * Class:     LWCNI
 * Method:    lwCConfine
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_LWCNI_lwCConfine
  (JNIEnv *, jclass);

/*
 * Class:     LWCNI
 * Method:    lwCCleanup
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_LWCNI_lwCCleanup
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
